name: ja-netfilter-nightly-build
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  set-up-jdk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Config Github Action Bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Update Submodules
        run: |
          git submodule init
          git submodule update
      - name: Set Up JDK8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'dragonwell'
      - name: Packaging core
        run: |
          mvn package -f ja-netfilter/pom.xml
      - name: Packaging plugin-dns
        run: |
          mvn package -f plugin-dns/pom.xml
      - name: Packaging plugin-power
        run: |
          mvn package -f plugin-power/pom.xml
      - name: Packaging plugin-url
        run: |
          mvn package -f plugin-url/pom.xml
      - name: Stage Artifacts
        run: |
          mkdir staging
          cp ja-netfilter/target/*-jar-with-dependencies.jar staging/
          cp plugin-dns/target/*-jar-with-dependencies.jar staging/
          cp plugin-power/target/*-jar-with-dependencies.jar staging/
          cp plugin-url/target/*-jar-with-dependencies.jar staging/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
