name: test
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  set-up-jdk:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Update Submodules
        run:  |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git submodule init
          git submodule update
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'dragonwell'
      - name: Packaging
        run: |
          mvn package -f ja-netfilter/pom.xml